use std::env;
use std::fs::{self, File};
use std::io::Write;
use std::path::Path;

const HEADER_GENERATED: &str = r#"
    // Auto-generated by build.rs
    use std::collections::HashMap;

    pub struct TestCaseData {
         pub content: &'static [u8],
         pub details: &'static str,
         pub typ: &'static str,
    }
    
    pub fn get_testcases_map() -> HashMap<u32, TestCaseData> {
        let mut m: HashMap<u32, TestCaseData> = HashMap::new();
"#;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let config_path = format!("{manifest_dir}/../testcases/config.json");

    let json_str = fs::read_to_string(&config_path).expect("Failed to read config.json");
    let json: serde_json::Value = serde_json::from_str(&json_str).expect("Invalid JSON");

    let testcases = json["testcases"]
        .as_array()
        .expect("Expected testcases array");

    let mut generated = String::new();
    generated.push_str(HEADER_GENERATED);

    for testcase in testcases {
        let id = testcase["id"].as_u64().expect("id missing") as u32;
        let file_path = testcase["file"].as_str().unwrap().replace("\"", "\\\"");
        let details = testcase["details"].as_str().unwrap().replace("\"", "\\\"");
        let typ = testcase["type"].as_str().unwrap().replace("\"", "\\\"");
        generated.push_str(&format!(
        "\t\tm.insert(\n\t\t\t{id},\n\t\t\tTestCaseData {{\n\t\t\t\tcontent: include_bytes!(\"../../{file_path}\"),\n\t\t\t\tdetails: \"{details}\",\n\t\t\t\ttyp: \"{typ}\"\n\t\t\t}}\n\t\t);\n"));
    }
    generated.push_str("    m\n}\n\n");

    let api_config_path = format!("{manifest_dir}/../testapi/config.json");
    let api_config_str =
        fs::read_to_string(&api_config_path).expect("Failed to read api_config.json");
    let api_config_json: serde_json::Value =
        serde_json::from_str(&api_config_str).expect("Invalid JSON");

    let apifiles = api_config_json["apifiles"]
        .as_array()
        .expect("Expected apifiles array");
    let idconfig = api_config_json["idconfig"]
        .as_str()
        .expect("Expected idconfig string");

    // Prepare code snippet for apifiles vec
    let mut api_files_code = String::new();
    api_files_code.push_str("pub fn get_api_files() -> Vec<&'static [u8]> {\n");
    api_files_code.push_str("    vec![\n");
    for file_value in apifiles {
        let file_path = file_value.as_str().unwrap();
        api_files_code.push_str(&format!("        include_bytes!(\"../{file_path}\"),\n"));
    }
    api_files_code.push_str("    ]\n}\n\n");

    // Prepare code snippet for idconfig standalone constant
    let idconfig_code =
        format!("pub const ID_CONFIG: &[u8] = include_bytes!(\"../{idconfig}\");\n");

    let out_path = Path::new(&manifest_dir).join("../generated/src/generated_assets.rs");
    let mut out_file = File::create(out_path).unwrap();
    out_file.write_all(generated.as_bytes()).unwrap();
    out_file.write_all(api_files_code.as_bytes()).unwrap();
    out_file.write_all(idconfig_code.as_bytes()).unwrap();
}
