window.rowtablebody = 'jstbody';
window.coltablebody = 'htmltbody';
window.colform = 'htmlform';
window.rowform = 'jsform';
window.defaultVisible = 'htmlsection';
window.hascheckbox = true;
window.checkboxId = 'tableselector'
window.checkboxdefault = false;
window.hasDropdown = false;
window.defaultSelected = '';
window.defaultEmpty=true;